name: "build"

on:
  push:
    branches: [ "**" ]
    tags-ignore: [ "**" ]
  pull_request:
  release:
    types: [ released ]

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: "${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}"

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: "Set up Java"
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "adopt"
      - name: "Cache Gradle"
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ secrets.CACHE_VERSION }}-

      - name: "Build"
        run: ./gradlew build dokkaHtmlMultiModule
      - name: "Upload test results artifact"
        uses: actions/upload-artifact@v2
        with:
          name: "test-results-${{ runner.os }}"
          path: |
            */build/reports/*

      - name: "Upload JAR artifact"
        uses: actions/upload-artifact@v2
        with:
          name: "jar"
          path: |
            */build/libs/*.jar
      - name: "Publish docs"
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: docs
          folder: build/dokka/htmlMultiModule
          target-folder: static/dokka
